### ISSUE TITLE
MCP230xx devices throw error on initialization

### ISSUE THREAD

**Issue by CrazyIvan359** [CrazyIvan359/mqttany#43]
### Describe the bug
A Type error occurs while initializing MCP230xx devices.

### Environment
- MQTTany version: 0.10.2

### Logs
```text
Configuring mcp23017 'Bus 2' at address 0x21 on bus '/dev/i2c-1'
An exception occurred while running function 'init'
Traceback (most recent call last):

  File "/opt/mqttany/mqttany/modules/__init__.py", line 124, in _call_func
    retval = func(**kwargs)

  File "/opt/mqttany/mqttany/modules/i2c/core.py", line 113, in init
    device_config

  File "/opt/mqttany/mqttany/modules/i2c/core.py", line 84, in build_device
    device_config

  File "/opt/mqttany/mqttany/modules/i2c/device/mcp230xx.py", line 539, in __init__
    self._pins = [None] * self._pin_max + 1

TypeError: can only concatenate list (not "int") to list

Module 'i2c' not initialized
```

**Comment by CrazyIvan359** [comment]
Fixed in [v0.10.3](https://github.com/CrazyIvan359/mqttany/releases/tag/v0.10.3)
